# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES="test-suite"
inherit haskell-cabal

DESCRIPTION="The command-line interface for Cabal and Hackage"
HOMEPAGE="http://www.haskell.org/cabal/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="debug-expensive-assertions debug-tracetree monolithic +network-uri parsec"

RDEPEND=">=dev-haskell/async-2.0:= <dev-haskell/async-2.2:=
	>=dev-haskell/base16-bytestring-0.1.1:= <dev-haskell/base16-bytestring-0.2:=
	>=dev-haskell/bytestring-builder-0.10:= <dev-haskell/bytestring-builder-1:=
	>=dev-haskell/cabal-2.0.0.0:= <dev-haskell/cabal-2.1:=
	>=dev-haskell/cryptohash-sha256-0.11:= <dev-haskell/cryptohash-sha256-0.12:=
	>=dev-haskell/echo-0.1.3:= <dev-haskell/echo-0.2:=
	>=dev-haskell/edit-distance-0.2.2:= <dev-haskell/edit-distance-0.3:=
	>=dev-haskell/hackage-security-0.5.2.2:= <dev-haskell/hackage-security-0.6:=
	>=dev-haskell/hashable-1.0:= <dev-haskell/hashable-2:=
	>=dev-haskell/http-4000.1.5:= <dev-haskell/http-4000.4:=
	>=dev-haskell/mtl-2.0:= <dev-haskell/mtl-2.3:=
	>=dev-haskell/old-time-1:= <dev-haskell/old-time-1.2:=
	>=dev-haskell/random-1:= <dev-haskell/random-1.2:=
	>=dev-haskell/stm-2.0:= <dev-haskell/stm-2.5:=
	>=dev-haskell/tar-0.5.0.3:= <dev-haskell/tar-0.6:=
	>=dev-haskell/zlib-0.5.3:= <dev-haskell/zlib-0.7:=
	>=dev-lang/ghc-7.4.1:=
	debug-tracetree? ( >=dev-haskell/tracetree-0.1:= <dev-haskell/tracetree-0.2:= )
	monolithic? ( dev-haskell/pretty-show:=
			>=dev-haskell/quickcheck-2.8.2:2=
			dev-haskell/tagged:=
			dev-haskell/tasty:=
			dev-haskell/tasty-hunit:=
			dev-haskell/tasty-quickcheck:= )
	network-uri? ( >=dev-haskell/network-2.6:= <dev-haskell/network-2.7:=
			>=dev-haskell/network-uri-2.6:= <dev-haskell/network-uri-2.7:= )
	!network-uri? ( >=dev-haskell/network-2.4:= <dev-haskell/network-2.6:=
			monolithic? ( dev-haskell/network-uri:= ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	network-uri? ( test? ( !monolithic? ( dev-haskell/pretty-show
						>=dev-haskell/quickcheck-2.8.2
						dev-haskell/tagged
						dev-haskell/tasty
						dev-haskell/tasty-hunit
						dev-haskell/tasty-quickcheck ) ) )
	!network-uri? ( monolithic? ( test? ( <dev-haskell/network-uri-2.6 ) )
			!monolithic? ( test? ( <dev-haskell/network-uri-2.6
						dev-haskell/pretty-show
						>=dev-haskell/quickcheck-2.8.2
						dev-haskell/tagged
						dev-haskell/tasty
						dev-haskell/tasty-hunit
						dev-haskell/tasty-quickcheck ) ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag debug-expensive-assertions debug-expensive-assertions) \
		$(cabal_flag debug-tracetree debug-tracetree) \
		$(cabal_flag monolithic monolithic) \
		$(cabal_flag network-uri network-uri) \
		$(cabal_flag parsec parsec)
}
