# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="memory and related abstraction stuff"
HOMEPAGE="https://github.com/vincenthz/hs-memory"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+support_basement +support_bytestring +support_deepseq +support_foundation"

RDEPEND=">=dev-lang/ghc-8.0.1:=
	support_basement? ( dev-haskell/basement:=[profile?] )
	support_foundation? ( dev-haskell/basement:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.0.0
	test? ( >=dev-haskell/basement-0.0.7
		dev-haskell/foundation )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag support_basement support_basement) \
		$(cabal_flag support_bytestring support_bytestring) \
		$(cabal_flag support_deepseq support_deepseq) \
		$(cabal_flag support_foundation support_foundation)
}
