# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="An efficient packed Unicode text type"
HOMEPAGE="https://github.com/haskell/text"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="developer integer-simple"

RDEPEND=">=dev-haskell/bytestring-builder-0.10.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	integer-simple? ( >=dev-haskell/integer-simple-0.1:=[profile?] <dev-haskell/integer-simple-0.5:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/hunit-1.2
		>=dev-haskell/quickcheck-2.7 <dev-haskell/quickcheck-2.11
		>=dev-haskell/quickcheck-unicode-1.0.1.0
		dev-haskell/random
		>=dev-haskell/test-framework-0.4
		>=dev-haskell/test-framework-hunit-0.2
		>=dev-haskell/test-framework-quickcheck2-0.2 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag developer developer) \
		$(cabal_flag integer-simple integer-simple)
}
